INSERT INTO TB_ESTADO VALUES ('PI', 'PIAUI');
INSERT INTO TB_ALUNO VALUES (15, 'CIPRIANO SOLON', 'RUA DOS PINHEIROS', 'PI', 1);
INSERT INTO TB_ALUNO VALUES (16, 'MARIA IOIÓ GOMES', 'RUA DOS PINHEIROS', 'PI', 4);
INSERT INTO TB_CLASSE VALUES (4, 3);
INSERT INTO TB_ALUNO_DISCIPLINA VALUES (16, 'MAT', 4);

SELECT * FROM TB_DISCIPLINA;

/* A1 */
SELECT COD_ALUNO, NOME_ALUNO FROM TB_ALUNO;

/* B1 */
SELECT NOME_ALUNO, ID_CLASSE FROM TB_ALUNO A
ORDER BY NOME_ALUNO ASC;

/* B2 - CASO INSIRA COD_ALUNO DIFERENTE DA SEQUENCIA, ELE ENTRA NO MEIO DOS CARACTERES */
SELECT NOME_ALUNO, ID_CLASSE, COD_ALUNO FROM TB_ALUNO A
ORDER BY CONVERT (COD_ALUNO, CHAR) DESC;

/* B3 - Selecionaremos  todos os alunos que cursam as disciplinas de matemática E de português agrupados por aluno e disciplina. */
 SELECT A.COD_ALUNO, NOME_ALUNO, ID_CLASSE FROM TB_ALUNO A
 INNER JOIN TB_ALUNO_DISCIPLINA B ON A.COD_ALUNO = B.COD_ALUNO
 INNER JOIN TB_DISCIPLINA C ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
 where C.NOME_DISCIPLINA = 'MATEMATICA'
 AND A.COD_ALUNO IN (
	 SELECT A.COD_ALUNO FROM TB_ALUNO A
	 INNER JOIN TB_ALUNO_DISCIPLINA B ON A.COD_ALUNO = B.COD_ALUNO
	 INNER JOIN TB_DISCIPLINA C ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
	 where C.NOME_DISCIPLINA = 'PORTUGUES'
 );
 
/* C1 - Queremos selecionar todos os nomes de alunos que cursam Português ou Matemática. */
 SELECT DISTINCT A.COD_ALUNO, NOME_ALUNO, ID_CLASSE FROM TB_ALUNO A
 INNER JOIN TB_ALUNO_DISCIPLINA B ON A.COD_ALUNO = B.COD_ALUNO
 INNER JOIN TB_DISCIPLINA C ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
 where (C.NOME_DISCIPLINA = 'MATEMATICA' 
	OR C.NOME_DISCIPLINA = 'PORTUGUES');
    
-- C2 - Queremos selecionar todos os nomes de alunos cadastrados que cursam  a disciplina FÍSICA e seus respectivos endereços
SELECT A.COD_ALUNO, A.NOME_ALUNO, A.END_ALUNO FROM TB_ALUNO A
INNER JOIN TB_ALUNO_DISCIPLINA B ON A.COD_ALUNO = B.COD_ALUNO
INNER JOIN TB_DISCIPLINA C ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
WHERE C.NOME_DISCIPLINA = 'FISICA';

SELECT * FROM TB_CLASSE;
-- C3 - Queremos selecionar todos os nomes de alunos cadastrados que cursam física e o andar que se encontra a classe dos mesmos. 
SELECT DISTINCT A.COD_ALUNO, A.NOME_ALUNO, A.ID_CLASSE, concat(D.ID_ANDAR, 'º Andar') 'ANDAR' FROM TB_ALUNO A
INNER JOIN TB_ALUNO_DISCIPLINA B ON A.COD_ALUNO = B.COD_ALUNO
INNER JOIN TB_DISCIPLINA C ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
INNER JOIN TB_CLASSE D ON A.ID_CLASSE = D.ID_CLASSE
WHERE C.NOME_DISCIPLINA = 'FISICA';

-- D1 - Selecionar todos os Professores com suas respectivas disciplinas e os demais Professores que não lecionam disciplina alguma.
SELECT A.NOME_PROFESSOR, B.NOME_DISCIPLINA FROM TB_PROFESSOR A
LEFT JOIN TB_DISCIPLINA B ON A.ID_PROFESSOR = B.ID_PROFESSOR_DISCIPLINA;

-- E1 -	Selecionar todos os nomes de professores que tenham ministrado disciplina para alunos que sejam do Estado do Piaui, cujo a classe tenha sido no terceiro andar.
SELECT DISTINCT A.NOME_PROFESSOR FROM TB_PROFESSOR A
WHERE A.ID_PROFESSOR IN (
	SELECT D.ID_PROFESSOR_DISCIPLINA FROM TB_DISCIPLINA D
    WHERE D.ID_DISCIPLINA IN (
		SELECT AD.ID_DISCIPLINA FROM TB_ALUNO_DISCIPLINA AD
        WHERE AD.COD_ALUNO IN (
			SELECT B.COD_ALUNO FROM TB_ALUNO B
            WHERE B.SIGLA_ESTADO IN (
				SELECT E.SIGLA_ESTADO FROM TB_ESTADO E
                WHERE E.NOME_ESTADO = 'PIAUI'
                AND B.ID_CLASSE IN (
					SELECT C.ID_CLASSE FROM TB_CLASSE C
						WHERE C.ID_ANDAR = 3)
		)
	)
)
);
